<a href="https://colab.research.google.com/github/ripro805/Campusx-DS-Mentorship/blob/main/session15_numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([89, 69, 28, 38, 95, 88, 99, 54, 22, 25, 59, 77, 30, 54, 52])

In [2]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[64, 16, 23, 80],
       [ 5, 55, 76, 22],
       [75, 79, 68, 57],
       [65, 10, 94, 92],
       [33, 46, 37, 31],
       [42, 67, 12, 63]])

In [3]:
np.sort(a)

array([22, 25, 28, 30, 38, 52, 54, 54, 59, 69, 77, 88, 89, 95, 99])

In [4]:
#descending
np.sort(a)[::-1]

array([99, 95, 89, 88, 77, 69, 59, 54, 54, 52, 38, 30, 28, 25, 22])

In [5]:
np.sort(b)

array([[16, 23, 64, 80],
       [ 5, 22, 55, 76],
       [57, 68, 75, 79],
       [10, 65, 92, 94],
       [31, 33, 37, 46],
       [12, 42, 63, 67]])

In [6]:
#columnwise
np.sort(b,axis=0)

array([[ 5, 10, 12, 22],
       [33, 16, 23, 31],
       [42, 46, 37, 57],
       [64, 55, 68, 63],
       [65, 67, 76, 80],
       [75, 79, 94, 92]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [7]:
# code
np.append(a,200)

array([ 89,  69,  28,  38,  95,  88,  99,  54,  22,  25,  59,  77,  30,
        54,  52, 200])

In [8]:
b

array([[64, 16, 23, 80],
       [ 5, 55, 76, 22],
       [75, 79, 68, 57],
       [65, 10, 94, 92],
       [33, 46, 37, 31],
       [42, 67, 12, 63]])

In [9]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[64.        , 16.        , 23.        , 80.        ,  0.76458709],
       [ 5.        , 55.        , 76.        , 22.        ,  0.56441217],
       [75.        , 79.        , 68.        , 57.        ,  0.95919959],
       [65.        , 10.        , 94.        , 92.        ,  0.70916201],
       [33.        , 46.        , 37.        , 31.        ,  0.32511573],
       [42.        , 67.        , 12.        , 63.        ,  0.16702574]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [10]:
# code
c=np.arange(6).reshape(2,3)
d=np.arange(12,18).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[12 13 14]
 [15 16 17]]


In [11]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [12]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [13]:
# code
e=np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [14]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [15]:
# code
a
#from 1d to 2d and 2d to 3d

array([89, 69, 28, 38, 95, 88, 99, 54, 22, 25, 59, 77, 30, 54, 52])

In [16]:
np.expand_dims(a,axis=1)

array([[89],
       [69],
       [28],
       [38],
       [95],
       [88],
       [99],
       [54],
       [22],
       [25],
       [59],
       [77],
       [30],
       [54],
       [52]])

In [17]:
np.expand_dims(a,axis=0)

array([[89, 69, 28, 38, 95, 88, 99, 54, 22, 25, 59, 77, 30, 54, 52]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [18]:
a

array([89, 69, 28, 38, 95, 88, 99, 54, 22, 25, 59, 77, 30, 54, 52])

In [19]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  1,  4,  5,  6,  7, 10, 11, 13, 14]),)

In [20]:
# replace all values > 50 with 0
#np.where(condition,true,false)
np.where(a>50,0,a)

array([ 0,  0, 28, 38,  0,  0,  0,  0, 22, 25,  0,  0, 30,  0,  0])

In [21]:
np.where(a%2==0,0,a)

array([89, 69,  0,  0, 95,  0, 99,  0,  0, 25, 59, 77,  0,  0,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [22]:
# code
a


array([89, 69, 28, 38, 95, 88, 99, 54, 22, 25, 59, 77, 30, 54, 52])

In [23]:
np.argmax(a)

np.int64(6)

In [24]:
b

array([[64, 16, 23, 80],
       [ 5, 55, 76, 22],
       [75, 79, 68, 57],
       [65, 10, 94, 92],
       [33, 46, 37, 31],
       [42, 67, 12, 63]])

In [25]:
np.argmax(b,axis=0)


array([2, 2, 3, 3])

In [26]:
np.argmax(b,axis=1)

array([3, 2, 1, 2, 1, 1])

In [27]:
# np.argmin
np.argmin(a)

np.int64(8)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [28]:
a

array([89, 69, 28, 38, 95, 88, 99, 54, 22, 25, 59, 77, 30, 54, 52])

In [29]:
np.cumsum(a)

array([ 89, 158, 186, 224, 319, 407, 506, 560, 582, 607, 666, 743, 773,
       827, 879])

In [30]:
np.cumsum(b,axis=1)

array([[ 64,  80, 103, 183],
       [  5,  60, 136, 158],
       [ 75, 154, 222, 279],
       [ 65,  75, 169, 261],
       [ 33,  79, 116, 147],
       [ 42, 109, 121, 184]])

In [31]:
np.cumsum(b,axis=0)

array([[ 64,  16,  23,  80],
       [ 69,  71,  99, 102],
       [144, 150, 167, 159],
       [209, 160, 261, 251],
       [242, 206, 298, 282],
       [284, 273, 310, 345]])

In [32]:
# np.cumprod

In [33]:
a

array([89, 69, 28, 38, 95, 88, 99, 54, 22, 25, 59, 77, 30, 54, 52])

In [34]:
np.cumprod(a)

array([                  89,                 6141,               171948,
                    6534024,            620732280,          54624440640,
              5407819623360,      292022259661440,     6424489712551680,
         160612242813792000, -8970621747695823616, -8208343845325008640,
       -6442642401526088192,  2585447718072718336,  5316072823814492160])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [35]:
a

array([89, 69, 28, 38, 95, 88, 99, 54, 22, 25, 59, 77, 30, 54, 52])

In [36]:
#NumPy তে percentile মানে হলো এমন একটি মান যা ডেটাসেটকে 100 সমান ভাগে ভাগ করলে নির্দিষ্ট শতাংশ ডেটা সেই মানের কম বা সমান হয়।
np.percentile(a,50)

np.float64(54.0)

In [37]:
np.percentile(a,0)

np.float64(22.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [38]:
# code
#NumPy তে histogram মানে হলো একটি ডেটাসেটকে interval বা bin এ ভাগ করে প্রতিটি bin-এ কতগুলো মান আছে তা গণনা করা।

#এটা মূলত ডেটা distribution বোঝার জন্য ব্যবহৃত হয়।
a

array([89, 69, 28, 38, 95, 88, 99, 54, 22, 25, 59, 77, 30, 54, 52])

In [39]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 0, 3, 2, 0, 4, 1, 1, 2, 2]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

Correlation coefficient (r) এমন একটি মান যা দুইটি ভেরিয়েবল কতটা linear relationship এ আছে তা বোঝায়।
এর মান -1 থেকে +1 এর মধ্যে থাকে:

+1 → perfect positive correlation

0 → no correlation

-1 → perfect negative correlation

In [40]:
salary=np.array([20000,40000,25000,35000,60000])
experience=np.array([1,3,2,4,2])

In [41]:
 np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [42]:
# code
a

array([89, 69, 28, 38, 95, 88, 99, 54, 22, 25, 59, 77, 30, 54, 52])

In [43]:
items = [10,20,30,40,50,60,70,80,90,100]

In [44]:
a[np.isin(a,items)]

array([30])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [45]:
# code
a

array([89, 69, 28, 38, 95, 88, 99, 54, 22, 25, 59, 77, 30, 54, 52])

In [46]:
np.flip(a)

array([52, 54, 30, 77, 59, 25, 22, 54, 99, 88, 95, 38, 28, 69, 89])

In [47]:
b

array([[64, 16, 23, 80],
       [ 5, 55, 76, 22],
       [75, 79, 68, 57],
       [65, 10, 94, 92],
       [33, 46, 37, 31],
       [42, 67, 12, 63]])

In [48]:
np.flip(b)

array([[63, 12, 67, 42],
       [31, 37, 46, 33],
       [92, 94, 10, 65],
       [57, 68, 79, 75],
       [22, 76, 55,  5],
       [80, 23, 16, 64]])

In [49]:
np.flip(b,axis=0)

array([[42, 67, 12, 63],
       [33, 46, 37, 31],
       [65, 10, 94, 92],
       [75, 79, 68, 57],
       [ 5, 55, 76, 22],
       [64, 16, 23, 80]])

In [50]:
np.flip(b,axis=1)

array([[80, 23, 16, 64],
       [22, 76, 55,  5],
       [57, 68, 79, 75],
       [92, 94, 10, 65],
       [31, 37, 46, 33],
       [63, 12, 67, 42]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [51]:
# code
a

array([89, 69, 28, 38, 95, 88, 99, 54, 22, 25, 59, 77, 30, 54, 52])

In [52]:
np.put(a,[0,1],[100,200])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [88]:
# code
a

array([[1.       , 2.       ],
       [3.       , 4.0000001]])

In [54]:
np.delete(a,[0,2,4])

array([200,  38,  88,  99,  54,  22,  25,  59,  77,  30,  54,  52])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [63]:
m=np.array([1,2,3,4,5])
n=np.array([3,4,5,6,7])
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [64]:
np.intersect1d(m,n)

array([3, 4, 5])

In [65]:
np.setdiff1d(m,n)

array([1, 2])

In [66]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [67]:
np.in1d(m,1)

/tmp/ipython-input-3930963099.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,1)


array([ True, False, False, False, False])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [92]:
# code
r= np.random.randint(1,100,15)
r.sort
r

array([ 1, 38, 77, 45,  2, 93, 44, 72, 76, 69, 35,  8, 76, 95, 17])

In [93]:
np.clip(r,a_min=25,a_max=75)

array([25, 38, 75, 45, 25, 75, 44, 72, 75, 69, 35, 25, 75, 75, 25])

#np.swapaxes

when you want to exchange (swap) two axes (dimensions) of an array.

In [68]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Original shape:", arr.shape)
print(arr)

swapped = np.swapaxes(arr, 0, 1)

print("\nAfter swapaxes(0, 1):")
print("New shape:", swapped.shape)
print(swapped)


Original shape: (2, 3)
[[1 2 3]
 [4 5 6]]

After swapaxes(0, 1):
New shape: (3, 2)
[[1 4]
 [2 5]
 [3 6]]


#np.uniform

It generates random floating-point numbers from a uniform distribution.

👉 Uniform distribution means every number in a given range has an equal chance of being selected.

In [69]:
arr = np.random.uniform(-3, 3, size=5)
print(arr)

[-1.90305793 -0.03547389 -0.8822008  -1.9388435  -0.03652583]


#np.count_nonzero

np.count_nonzero(array) counts how many elements in the array are non-zero (i.e., not equal to 0 or False).

In [70]:
import numpy as np

arr = np.array([0, 1, 2, 0, 3, 0, 4])

print(np.count_nonzero(arr))


4


In [71]:
arr2 = np.array([[0, 1, 0],
                 [2, 0, 3],
                 [4, 5, 0]])

print(np.count_nonzero(arr2))              # total count
print(np.count_nonzero(arr2, axis=0))      # count column-wise
print(np.count_nonzero(arr2, axis=1))      # count row-wise


5
[2 2 1]
[1 2 2]


#np.tile

Construct an array by repeating A the number of times given by reps.
 https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [72]:
# 21. np.tile
import numpy as np

a = np.array([1, 2, 3])
print(np.tile(a, 2))   # repeat twice
print(np.tile(a, 3))   # repeat three times


[1 2 3 1 2 3]
[1 2 3 1 2 3 1 2 3]


In [73]:
b = np.array([[1, 2],
              [3, 4]])

print(np.tile(b, 2))       # repeat across columns
print(np.tile(b, (2, 1)))  # repeat across rows
print(np.tile(b, (2, 2)))  # repeat both rows & columns


[[1 2 1 2]
 [3 4 3 4]]
[[1 2]
 [3 4]
 [1 2]
 [3 4]]
[[1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]]


# np.repeat

np.repeat repeats elements of an array.
https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [74]:
# 22. np.repeat
import numpy as np

a = np.array([1, 2, 3])
print(np.repeat(a, 2))  # repeat each element 2 times


[1 1 2 2 3 3]


In [75]:
a = np.array([10, 20, 30])
print(np.repeat(a, [1, 2, 3]))


[10 20 20 30 30 30]


In [76]:
a = np.array([[1, 2], [3, 4]])
print(np.repeat(a, 2))


[1 1 2 2 3 3 4 4]


In [77]:
a = np.array([[1, 2], [3, 4]])
print(np.repeat(a, 2, axis=0))


[[1 2]
 [1 2]
 [3 4]
 [3 4]]


In [78]:
a = np.array([[1, 2], [3, 4]])
print(np.repeat(a, 2, axis=1))


[[1 1 2 2]
 [3 3 4 4]]


#np.allclose and equals

**np.allclose**

Checks if two arrays are element-wise equal within a tolerance.

In [79]:
# 25. np.allclose
import numpy as np

a = np.array([1.0, 2.0, 3.0000001])
b = np.array([1.0, 2.0, 3.0])

print(np.allclose(a, b))   # True (because difference is tiny)


True


In [80]:
print(np.allclose(a, b, atol=1e-10))  # False (now tolerance is too strict)


True


**np.array_equals**

Checks if two arrays are exactly the same (shape and values).

In [81]:
x = np.array([1.0, 2.0, 3.0000001])
y = np.array([1.0, 2.0, 3.0])

print(np.array_equal(x, y))  # False (not exactly equal)


False


In [82]:
import numpy as np

a = np.array([[1.0, 2.0], [3.0, 4.0000001]])
b = np.array([[1.0, 2.0], [3.0, 4.0]])

print("2D allclose:", np.allclose(a, b))      # ?
print("2D array_equal:", np.array_equal(a, b)) # ?


2D allclose: True
2D array_equal: False


In [84]:
x = np.array([[[1.0, 2.0], [3.0, 4.00000001]]])
y = np.array([[[1.0, 2.0], [3.0, 4.0]]])

print("3D allclose:", np.allclose(x, y))      # ?
print("3D array_equal:", np.array_equal(x, y)) # ?


3D allclose: True
3D array_equal: False


In [85]:
m = np.array([[1, 2, 3]])
n = np.array([1, 2, 3])

print(np.allclose(m, n))      # ?
print(np.array_equal(m, n))   # ?


True
False
