<a href="https://colab.research.google.com/github/ripro805/Campusx-DS-Mentorship/blob/main/session_13_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Create numpy array

In [ ]:
#1D array or vector
import numpy as np

a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
#2D array or mattrice
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
#3d or tensor
c=np.array([[[1,2],[4,5]],[[6,8],[11,12]]])
print(c)

[[[ 1  2]
  [ 4  5]]

 [[ 6  8]
  [11 12]]]


In [ ]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
# with reshape
np.arange(1,16).reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.random.random((3,4))

array([[0.18168779, 0.46864151, 0.67562666, 0.29302376],
       [0.65746147, 0.46996344, 0.83594364, 0.35739243],
       [0.13745555, 0.74410965, 0.25153079, 0.36666154]])

In [ ]:
np.linspace(-7,10,20)

array([-7.        , -6.10526316, -5.21052632, -4.31578947, -3.42105263,
       -2.52631579, -1.63157895, -0.73684211,  0.15789474,  1.05263158,
        1.94736842,  2.84210526,  3.73684211,  4.63157895,  5.52631579,
        6.42105263,  7.31578947,  8.21052632,  9.10526316, 10.        ])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes

In [ ]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3.ndim

3

In [ ]:
a2.shape

(3, 4)

In [ ]:
a2.size

12

In [ ]:
a1.itemsize

8

In [ ]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


In [ ]:
a2.astype(np.int32)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)

#Array Operations

In [ ]:
a1= np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

#Array function

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[98., 43., 67.],
       [56., 88., 35.],
       [19., 14., 80.]])

In [ ]:
# mean/median/std/var
# 0 -> col and 1 -> row
print(np.mean(a1)) #mean in full
print(np.median(a1))#median in full
print(np.std(a1))#std in full
print(np.var(a1))#varuct in full
print(np.mean(a1,axis=0))#mean in col
print(np.median(a1,axis=0))#median in col
print(np.std(a1,axis=0))#std in col
print(np.var(a1,axis=1))#var in row
print(np.var(a1,axis=0))#var in col

55.55555555555556
56.0
28.33572974615112
802.9135802469135
[57.66666667 48.33333333 60.66666667]
[56. 43. 67.]
[32.27313985 30.44484996 18.90913947]
[506.88888889 474.88888889 900.22222222]
[1041.55555556  926.88888889  357.55555556]


In [ ]:
# max/min/sum/prod
# 0 -> col and 1 -> row
print(np.max(a1)) #max in full
print(np.min(a1))#min in full
print(np.sum(a1))#sum in full
print(np.prod(a1))#product in full
print(np.max(a1,axis=0))#max in col
print(np.min(a1,axis=0))#min in col
print(np.sum(a1,axis=0))#sum in col
print(np.prod(a1,axis=1))#prod in row
print(np.prod(a1,axis=0))#prod in col

98.0
14.0
500.0
1036286167347200.0
[98. 88. 80.]
[19. 14. 35.]
[173. 145. 182.]
[282338. 172480.  21280.]
[104272.  52976. 187600.]


In [ ]:
#dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log and exponents

print(np.log(a1))
print(np.exp(a1))


[[4.58496748 3.76120012 4.20469262]
 [4.02535169 4.47733681 3.55534806]
 [2.94443898 2.63905733 4.38202663]]
[[3.63797095e+42 4.72783947e+18 1.25236317e+29]
 [2.09165950e+24 1.65163625e+38 1.58601345e+15]
 [1.78482301e+08 1.20260428e+06 5.54062238e+34]]


In [ ]:
# round/floor/ceil
print(np.round(np.random.random((2,3))*100))
print(np.floor(np.random.random((2,3))*100))
print(np.ceil(np.random.random((2,3))*100))

[[38. 30. 24.]
 [39. 90. 14.]]
[[59. 90. 58.]
 [37. 32.  0.]]
[[ 7. 52. 38.]
 [83. 50. 15.]]


# Indexing and Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
int(a1[-1])

9

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
int(a2[1,1])

5

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
int(a3[1,0,1])

5

In [ ]:
a2[1,::3]

array([4, 7])

In [ ]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
a1[2:5:2]

array([2, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1,::3]

array([4, 7])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[1,0:,1]

array([10, 13, 16])

 # Iterating


In [ ]:
a1
for i in a1 :
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2
for i in a2 :
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a3
for i in a3 :
  print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [ ]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


#Reshaping

In [ ]:
#reshape

In [ ]:
#Transpose

a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
#ravel
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Stacking

In [ ]:
#horizontal
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
#vertical
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#Splitting


In [ ]:
# horizontal splitting
a4
np.hsplit(a4,3)

ValueError: array split does not result in an equal division

In [ ]:
# vertical splitting
a5
np.vsplit(a5,2)

ValueError: array split does not result in an equal division