<a href="https://colab.research.google.com/github/ripro805/Campusx-DS-Mentorship/blob/main/Task_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [ ]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [ ]:
#Code here
arr=np.zeros(10)
arr[4]=1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
#Code here
a=int(input())
b=int(input())
arr=np.random.rand(a,b)
print(arr)
print(np.mean(arr))

4
3
[[0.11718477 0.38305064 0.53886016]
 [0.21688694 0.14038299 0.79790623]
 [0.86864964 0.40716571 0.94319084]
 [0.72113886 0.10164922 0.83635196]]
0.5060348298999423


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [ ]:
#Code here
arr=np.ones((5,5))
arr[1:-1,1:-1]=0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [ ]:
#Code here
arr=np.linspace(0,1,12)[1:-1]
arr

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
#Code here
arr=np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
#Code here

arr=np.zeros((5,5))
arr+=np.arange(5)
arr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [ ]:
#code here
points=np.random.randint(1,100,(10,2))
point=np.array([2,3])
distance=np.sqrt(np.sum((points-point)**2,axis=1))
distance

array([ 84.14867795,  65.51335742,  94.79451461,  36.05551275,
        78.77182237,  49.04079934,  56.46237685,  91.48223871,
       113.40634903,  75.96051606])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
#Code here
arr=(6,7,8)
indx=np.unravel_index(100,(6,7,8))
print(indx)

(np.int64(1), np.int64(5), np.int64(4))


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
#Code here
a=input()
arr=np.array(a.split(),dtype=float)
rev=arr[::-1]
print(rev)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [ ]:
#Code here
arr=np.array([1,2,3,4,5])
print(len(arr))

5


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
#Code here

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
#Coder here
a = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9]])

b = np.array([[1, 1, 1, 1, 1],
              [1, 1, 1, 1, 1]])

c = np.array([[0.10117373, 0.1677244,  0.73764059, 0.83166097, 0.48985695],
              [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

res = np.vstack((a, b, c))

print(res)

[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
#Code here


###`Q-14:` Subtract the mean of each row from a matrix.

In [ ]:
#code here
mat=np.random.randint(1,10,(3,3))
print(mat)
print(mat-np.mean(mat,axis=1,keepdims=True))

[[9 8 5]
 [6 9 8]
 [4 8 8]]
[[ 1.66666667  0.33333333 -1.66666667]
 [-1.33333333  1.33333333  1.33333333]
 [-3.33333333  0.33333333  1.33333333]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
#Code here
arr=np.arange(9).reshape(3,3)
print(arr)
arr[:,[0,1]]=arr[:,[1,0]]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


###`Q-16:` Replace odd elements in arrays with -1.

In [ ]:
#Code here
arr=np.arange(10)
arr[arr%2==1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [ ]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
res=np.maximum(a,b)
res

array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [ ]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[ 274, 9957,  364,  717, 2643],
       [7063, 7688, 8993, 5367, 9985],
       [4500, 2350, 1767, 1570, 6012],
       [ 689, 3690, 6672, 6312, 2633],
       [1185, 8101, 9791, 8079, 4742],
       [2242, 2592, 8590, 9464, 7877],
       [6054, 4202, 5063, 1185, 6373],
       [6334, 4689, 4133, 4520, 8612]])

In [ ]:
#Code here
print(arr1[:,::2])
xmin,xmax=arr1.min(),arr1.max()
norm=(arr1-xmin)/(xmax-xmin)
print(norm)

[[ 274  364 2643]
 [7063 8993 9985]
 [4500 1767 6012]
 [ 689 6672 2633]
 [1185 9791 4742]
 [2242 8590 7877]
 [6054 5063 6373]
 [6334 4133 8612]]
[[0.         0.99711667 0.00926784 0.04561837 0.24395016]
 [0.69910411 0.76346411 0.8978478  0.5244568  1.        ]
 [0.4351766  0.21377819 0.15374318 0.1334569  0.59087633]
 [0.04273504 0.35176604 0.65884049 0.62176913 0.2429204 ]
 [0.09381114 0.8059932  0.98002265 0.80372773 0.4600968 ]
 [0.20265678 0.23869838 0.85634847 0.9463495  0.78292658]
 [0.59520132 0.40448975 0.4931521  0.09381114 0.62805066]
 [0.6240346  0.45463907 0.39738441 0.43723612 0.85861394]]


###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [ ]:
#Code here

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [ ]:
#code here
a=np.array([1,2,3])
part1 = np.repeat(a, 3)
part2 =np.tile(a,3)
res=np.concatenate((part1,part2))
res

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])