<a href="https://colab.research.google.com/github/ripro805/Campusx-DS-Mentorship/blob/main/Task_15_numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [15]:
# code here
import numpy as np
np.random.seed(0 )
arr=np.random.randint(0,101,size=(4,3))
arr

array([[44, 47, 64],
       [67, 67,  9],
       [83, 21, 36],
       [87, 70, 88]])

In [16]:
np.sort(arr)

array([[44, 47, 64],
       [ 9, 67, 67],
       [21, 36, 83],
       [70, 87, 88]])

In [17]:
based_on_2nd_column=arr[arr[:,1].argsort()]
based_on_2nd_column

array([[83, 21, 36],
       [44, 47, 64],
       [67, 67,  9],
       [87, 70, 88]])

In [18]:
row_max=arr[arr.max(axis=1).argsort()]
row_max

array([[44, 47, 64],
       [67, 67,  9],
       [83, 21, 36],
       [87, 70, 88]])

In [19]:
el=np.sort(arr, axis=None).reshape(arr.shape)
el

array([[ 9, 21, 36],
       [44, 47, 64],
       [67, 67, 70],
       [83, 87, 88]])

###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [21]:
# code here
import numpy as np

# Given data
marks = np.array([[13, 10,  9, 33],
                  [63, 46, 90, 42],
                  [39, 76, 13, 29],
                  [82,  9, 29, 78],
                  [67, 61, 59, 36]])

extra_subject = np.array([41, 87, 72, 36, 92])

# Step i: Add marks of extra subject to existing students
marks = np.hstack((marks, extra_subject.reshape(-1, 1)))
print("After adding extra subject:\n", marks)

# Step ii: Add two new students (5 subjects now)
rec1 = np.array([77, 83, 98, 95, 89])
rec2 = np.array([92, 71, 52, 61, 53])
marks = np.vstack((marks, rec1, rec2))
print("\nAfter adding two new students:\n", marks)

# Step iii: Add extra column with sum of all subjects
total_marks = marks.sum(axis=1).reshape(-1, 1)
marks_with_total = np.hstack((marks, total_marks))
print("\nAfter adding total marks column:\n", marks_with_total)

# Step iv: Sort array by total marks column (non-ascending) and show top 2 rows
sorted_marks = marks_with_total[marks_with_total[:, -1].argsort()[::-1]]
top2 = sorted_marks[:2]
print("\nTop 2 students based on total marks:\n", top2)


After adding extra subject:
 [[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]]

After adding two new students:
 [[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]
 [77 83 98 95 89]
 [92 71 52 61 53]]

After adding total marks column:
 [[ 13  10   9  33  41 106]
 [ 63  46  90  42  87 328]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]

Top 2 students based on total marks:
 [[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]


###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [26]:
# code here
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,2]])
row_wise=np.unique(arr,axis=0)
col_wise=np.unique(arr,axis=1)
print("Row Wise:\n",row_wise)
print("Col Wise:\n",col_wise)

Row Wise:
 [[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 3 1 2]
 [1 2 3 8 8 8]]
Col Wise:
 [[1 1 1 2 3 3]
 [0 8 8 9 1 2]
 [1 8 8 2 3 8]
 [1 1 2 2 3 3]]


###`Q-4:` Flip given 2-D array along both axes at the same time.

In [27]:
# code here
np.flip(arr)

array([[2, 1, 3, 3, 2, 1],
       [8, 8, 8, 3, 2, 1],
       [8, 8, 2, 1, 9, 0],
       [1, 1, 3, 3, 2, 1]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [30]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],
                [10, -3, 30, 4, 5],
                [3, 2, 5, -4, 5],
                [9, 7, 3, 6, 5]])

X = 6

# Get row indices where any element > X
rows_with_large_element = np.where(np.any(arr > X, axis=1))[0]

print("Row numbers with element larger than", X, ":", rows_with_large_element)


Row numbers with element larger than 6 : [1 3]


### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [31]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [32]:
# code here
flat_array = np.hstack((arr1, arr2, arr3))
print(flat_array)


[0 1 2 3 4 5 6 7 8 9]


### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [33]:
# code here
import numpy as np

# Seed and array
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))



# Find min and max values
min_val = arr.min()
max_val = arr.max()

print("Minimum value:", min_val)
print("Maximum value:", max_val)

# Remove min and max from the array
arr_filtered = arr[(arr != min_val) & (arr != max_val)]

print("Array after removing min and max:", arr_filtered)


Minimum value: 103
Maximum value: 998
Array after removing min and max: [448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
 181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
 353 975 592 997 137 340 222 215 472 459 617 649 935 956 914 932 645 952
 921 490 527 972 278 307 840 958 246 449 251 957 627 920 824 356 825 173
 323 372 960 710 464 244 782 763 635 436 774 171 469 178 458 624 211 771
 270 308 231 952 514 699 702 433 900 373 318 265 503 320 230 324 922 967
 620 743 527 117 566 804 123 946 587 227 853 757 944 328 855 930 325 729
 426 514 296 879 575 936 705 209 191 743 510 513 628 559 658 528 395 525
 922 136 496 225 895 975 263 908 420 711 800 976 786 235 930 859 618 226
 695 460 218 483 490 803 621 453 193 607 677 637 728 724 534 748 291 194
 761 875 687 569 228 482 781 554 654 739 885 197 266 228 892 207 883 588]


### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [34]:
# code here
import numpy as np

# Example array
np.random.seed(42)
arr = np.random.randint(100, 700, 20)
print("Original array:\n", arr)

# Step 1: Clip the array between 100 and 200
arr_clipped = np.clip(arr, 100, 200)
print("\nClipped array (100 to 200):\n", arr_clipped)

# Step 2: Sort the array
arr_sorted = np.sort(arr_clipped)
print("\nSorted array:\n", arr_sorted)

# Step 3: Compute cumulative sum
arr_cumsum = np.cumsum(arr_sorted)
print("\nCumulative sum of sorted array:\n", arr_cumsum)


Original array:
 [202 535 370 206 171 120 221 566 314 430 558 187 472 199 230 408 443 591
 513 485]

Clipped array (100 to 200):
 [200 200 200 200 171 120 200 200 200 200 200 187 200 199 200 200 200 200
 200 200]

Sorted array:
 [120 171 187 199 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200]

Cumulative sum of sorted array:
 [ 120  291  478  677  877 1077 1277 1477 1677 1877 2077 2277 2477 2677
 2877 3077 3277 3477 3677 3877]


### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [35]:
# code here
import numpy as np

# Example array
np.random.seed(42)
arr = np.random.rand(20)  # values in [0,1]
print("Original array:\n", arr)

# Step 1: Round elements to 3 decimal places
arr_rounded = np.round(arr, 3)
print("\nRounded array (3 decimals):\n", arr_rounded)

# Step 2: Compare 0th and 100th percentile with min and max
percentile_0 = np.percentile(arr_rounded, 0)
percentile_100 = np.percentile(arr_rounded, 100)
min_val = arr_rounded.min()
max_val = arr_rounded.max()

print("\n0th percentile:", percentile_0, "== min value:", min_val)
print("100th percentile:", percentile_100, "== max value:", max_val)

# Step 3: Find difference between 51st and 50th percentiles
percentile_50 = np.percentile(arr_rounded, 50)
percentile_51 = np.percentile(arr_rounded, 51)
diff = percentile_51 - percentile_50

print("\n50th percentile:", percentile_50)
print("51st percentile:", percentile_51)
print("Difference (51th - 50th percentile):", diff)


Original array:
 [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985
 0.83244264 0.21233911 0.18182497 0.18340451 0.30424224 0.52475643
 0.43194502 0.29122914]

Rounded array (3 decimals):
 [0.375 0.951 0.732 0.599 0.156 0.156 0.058 0.866 0.601 0.708 0.021 0.97
 0.832 0.212 0.182 0.183 0.304 0.525 0.432 0.291]

0th percentile: 0.021 == min value: 0.021
100th percentile: 0.97 == max value: 0.97

50th percentile: 0.40349999999999997
51st percentile: 0.41433
Difference (51th - 50th percentile): 0.010830000000000006
